name: EHR Deploy Main

on:
  push:
    branches: [master]

env:
  IMAGE_NAME: "avita"
  IMAGE_SUFFIX: "main-latest"
  REGISTRY_USER: "jvsm123"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Avita Registry
        uses: docker/login-action@v3
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ env.IMAGE_NAME }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_SUFFIX }}-${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: Move Buildx Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: SED docker-compose and point to image
        run: |
          sed -i 's|image: avita|image: '"${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_SUFFIX }}-${{ github.sha }}"'|g' ./docker-compose.yml

      - name: Upload docker-compose
        uses: nicklasfrahm/scp-action@main
        with:
          direction: upload
          key: ${{ secrets.SSH_KEY}}
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          insecure_ignore_fingerprint: true
          username: ${{ secrets.SSH_USER }}

          source: ./docker-compose.yml
          target: "~/avita/docker-compose.yml"

      - name: SSH on VM
        uses: nekiro/ssh-job@main
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          command: |
            docker stop avita ; docker container rm avita ; docker image rm ${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_SUFFIX }}-${{ github.sha }} ; docker compose -f ~/avita/docker-compose.yml up -d ; exit
